#!/usr/bin/env python3
"""Batch-replace the legacy 'Z' logo-icon with the new favicon.svg infinity icon."""
import re
from pathlib import Path

ROOT = Path("D:/Users/taojiang/Documents/GitHub/ZenTools")

# Exact inline div generated by _batch_unify_ui.py
INLINE_DIV_RE = re.compile(
    r'<div\s+class="logo-icon"\s+style="width:36px;height:36px;border-radius:50%;background:var\(--zen-gradient\);display:flex;align-items:center;justify-content:center;color:#fff;font-size:20px;font-weight:700">Z</div>',
    re.IGNORECASE
)
INLINE_REPLACE = '<img src="/favicon.svg" class="logo-icon" alt="ZenTools" style="width:36px;height:36px;border-radius:50%;background:var(--zen-gradient);object-fit:contain;padding:6px;box-sizing:border-box;">'

# External-style divs (Z-only)
EXTERNAL_DIV_RE = re.compile(r'<div\s+class="logo-icon">Z</div>', re.IGNORECASE)
EXTERNAL_REPLACE = '<img src="/favicon.svg" class="logo-icon" alt="ZenTools">'

CSS_RULE_RE = re.compile(r'(\.logo-icon\s*\{)([^{}]*)(\})', re.IGNORECASE | re.DOTALL)


def rewrite_css_rule(match):
    props = match.group(2)
    # Desktop main rule: contains full text-styling set
    if ('font-weight' in props and '700' in props) or ('display' in props and 'flex' in props):
        return '.logo-icon { width: 36px; height: 36px; border-radius: 50%; background: var(--zen-gradient); object-fit: contain; padding: 6px; box-sizing: border-box; }'
    # Mobile / media-query rule: only width/height/font-size
    if ('font-size' in props and '16px' in props) or ('width' in props and '30px' in props):
        return '.logo-icon { width: 30px; height: 30px; object-fit: contain; padding: 5px; box-sizing: border-box; }'
    return match.group(0)


def process_file(path):
    content = path.read_text(encoding='utf-8', errors='ignore')
    original = content

    # 1. Replace inline-style Z divs
    content = INLINE_DIV_RE.sub(INLINE_REPLACE, content)
    # 2. Replace external-style Z divs
    content = EXTERNAL_DIV_RE.sub(EXTERNAL_REPLACE, content)
    # 3. Update CSS rules on pages that still have a .logo-icon rule
    if re.search(r'\.logo-icon\s*\{', content):
        content = CSS_RULE_RE.sub(rewrite_css_rule, content)

    if content != original:
        path.write_text(content, encoding='utf-8')
        return True
    return False


def main():
    files = [f for f in ROOT.rglob("*.html") if '.bak' not in f.name]
    updated = 0
    errors = []
    for i, f in enumerate(files):
        try:
            if process_file(f):
                updated += 1
                if updated % 50 == 0:
                    print(f"  updated {updated} ...")
        except Exception as e:
            errors.append((str(f), str(e)))
    print(f"Done. {updated} files updated.")
    if errors:
        print(f"Errors ({len(errors)}):")
        for p, e in errors[:10]:
            print(f"  {p}: {e}")


if __name__ == '__main__':
    main()
